// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  experience: dynamic(() => import("./Timeline")),
  hero: dynamic(() => import("./Hero")),
  rich_text: dynamic(() => import("./RichText")),
  services: dynamic(() => import("./Services")),
  skills: dynamic(() => import("./Skills")),
  works: dynamic(() => import("./Works")),
};
